### ISSUE TITLE
The user's GIF collection seems to be missing on iPad

### ISSUE THREAD

**Issue by SebinNyshkim** [peter-iakovlev/Telegram#104]
I've noticed that the button for saved GIFs is missing on the iPad in Telegram.

When going into the stickers panel on iPhone there's a GIF button to easily select any GIF you recently sent.
When going into the stickers panel on iPad, there is nothing. And the @ gif inline bot doesn't provide that functionality and doesn't include user created GIFs either.

I suspect the stickers selection acts as its own in-app keyboard. Maybe the button is just missing?

**Comment by seantanly** [comment]
+1

**Comment by RedFoxy** [comment]
Still missing...

**Comment by boaerosuke** [comment]
is it a bug or a feature?

**Comment by RedFoxy** [comment]
funny... but still missing!

**Comment by kkiani** [comment]
No fixes yet!! It’s very annoying!!

**Comment by plusreed** [comment]
I asked someone more knowledgeable about this a while ago, I got this response back:

> I believe it's disabled for iPad due to iPad having a larger screen, which can show more GIFs on the screen at once. However, the iOS platform has limitations on rendering multiple videos on the screen at once.

**Comment by kkiani** [comment]
it’s silly way to solve this kind of problem!! because they can limit size of gif tab or stop playing all of them at once, just showing the first frame only to choose!

**Comment by plusreed** [comment]
I personally do agree that it seems like a lazy way of “solving” the issue. (solving in quotation marks because it’s not really a solution imho. 😕)

> because they could limit size of gif tab

I personally think this could work. I don’t know the exact limitations of iOS with rendering of videos but this seems like it could work.

> stop playing all of them at once, just showing the first frame only to choose!

I feel as if this wouldn’t be a great solution, some of the gifs I have look similar on the first frame. I feel as if it could cause some confusion.

The way I’m thinking is that as you scroll, past gifs will stop playing to circumvent the rendering limitations and new ones begin playing. (I’m not an iOS app developer, so I don’t know how easy/hard this would be.)

Maybe the iOS dev should comment on this. It would probably be better to tell them how we think the GIF tab should be implemented on iPad, and see if they’re interested in enabling it.

**Comment by SebinNyshkim** [comment]
Building upon the suggestion that all GIFs don't play all at once because of iOS limitations:

How about making the preview images bigger so that it is still is within the limitations of iOS and can still play all at once. Another way I can think of is playing each individual GIF in an enlarged view, kind of in the way that stickers enlarge when you long-press/force-press them on an iPhone.

**Comment by RedFoxy** [comment]
iPhone does, just give us like iPhone and not bigger, when you have a solution make it bigger, or put it with still images but put it!

**Comment by plusreed** [comment]
I just talked to the iOS dev, he says the GIF panel should be on the iPad in the next update.

**Comment by SebinNyshkim** [comment]
Still no GIF panel on iPad after update

**Comment by Nemanja1024** [comment]
+1

**Comment by iluzahen** [comment]
+1

**Comment by NapStudio** [comment]
There is no plan to solve this?

**Comment by vsg24** [comment]
To stupidity and beyond...

**Comment by plusreed** [comment]
Hi, it’s been a while since I commented on this issue but the GIF panel is available on the alternative Swift client, also known as [Telegram X](https://itunes.apple.com/us/app/telegram-x/id898228810?mt=8).

![d3226ebd-5b9f-42f9-8d10-881e36d0e161](https://user-images.githubusercontent.com/5272976/34408039-801f1578-eb8f-11e7-9c1a-89899f5bf04b.jpeg)

If you want a GIF panel on Telegram for iPad, you should try using Telegram X. It _should_ be there.

**Comment by SebinNyshkim** [comment]
In a previous update to the regular Telegram Client for iOS the GIF panel was added to the iPad version. I thought devs would've closed this when they released the update, but apparently not. Weird. I'll close the issue myself.
